In [1]:
#Importing Libraries
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
#loading the datafile from the given location
file = 'https://aegis4048.github.io/downloads/notebooks/sample_data/unconv_MV_v5.csv'
df = pd.read_csv(file)

In [3]:
#marking the features required and the target data
features = ['Por', 'Brittle', 'Perm', 'TOC']
target = 'Prod'

#Reshaping X and Y values
X = df[features].values.reshape(-1, len(features))
y = df[target].values

In [4]:
#fiting the models
ols = linear_model.LinearRegression()
model = ols.fit(X, y)

In [5]:
model.coef_

array([244.60011793,  31.58801063,  86.87367291, 325.19354135])

In [6]:
model.intercept_

-1575.2734966267162

In [7]:
model.score(X, y)

0.9516996043535946

In [8]:
x_pred = np.array([12, 81, 2.31, 2.8])
x_pred = x_pred.reshape(-1, len(features))

In [9]:
model.predict(x_pred)

array([5029.77688021])

In [10]:
#Now making prediction of 2 gases production rate
"""Por = 12 (%)
Brittle = 81 (%)
VR = 2.31 (%)
AI = 2.8 (kg/m2s*10^6)"""

"""Por = 15 (%)
Brittle = 60 (%)
VR = 2.5 (%)
AI = 1 (kg/m2s*10^6)"""

x_pred = np.array([[12, 81, 2.31, 2.8], [15, 60, 2.5, 1]])
x_pred = x_pred.reshape(-1, len(features))

In [11]:
model.predict(x_pred)

array([5029.77688021, 4531.3866341 ])