In [1]:
import numpy as np

In [2]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]

In [3]:
print(type(data_type))

<class 'list'>


In [4]:
print(type(data_type[0]))

<class 'tuple'>


In [5]:
print(type(students_details))

<class 'list'>


In [6]:
print(type(students_details[0]))

<class 'tuple'>


In [7]:
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]


In [8]:
print(type(students))

<class 'numpy.ndarray'>


In [9]:
print(np.size(students))

4


In [10]:
print("Sort by height")
print(np.sort(students, order='height'))

Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [11]:
matrix_a = np.arange(9, dtype=float).reshape(3, 3)
print("Matrix 'matrix_a':")
print(matrix_a)

Matrix 'matrix_a':
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [12]:
print(matrix_a[0])

[0. 1. 2.]


In [13]:
print(matrix_a[0][1])

1.0


In [15]:
print(matrix_a[0,2])

2.0


In [18]:
array_b = np.array([10, 11, 12])
print("\nArray 'array_b':")
print(array_b)


Array 'array_b':
[10 11 12]


In [19]:
print(array_b[1])

11


In [20]:
print("\nElement-wise addition of 'matrix_a' and 'array_b':")
print(np.add(matrix_a, array_b))


Element-wise addition of 'matrix_a' and 'array_b':
[[10. 12. 14.]
 [13. 15. 17.]
 [16. 18. 20.]]


In [21]:
print("\nElement-wise subtraction of 'array_b' from 'matrix_a':")
print(np.subtract(matrix_a, array_b))


Element-wise subtraction of 'array_b' from 'matrix_a':
[[-10. -10. -10.]
 [ -7.  -7.  -7.]
 [ -4.  -4.  -4.]]


In [22]:
print("\nElement-wise multiplication of 'matrix_a' and 'array_b':")
print(np.multiply(matrix_a, array_b))


Element-wise multiplication of 'matrix_a' and 'array_b':
[[ 0. 11. 24.]
 [30. 44. 60.]
 [60. 77. 96.]]


In [23]:
print("\nElement-wise division of 'matrix_a' by 'array_b':")
print(np.divide(matrix_a, array_b))


Element-wise division of 'matrix_a' by 'array_b':
[[0.         0.09090909 0.16666667]
 [0.3        0.36363636 0.41666667]
 [0.6        0.63636364 0.66666667]]


In [24]:
print(np.size(matrix_a))

9


In [25]:
matrix_a_2 = matrix_a.reshape(3, 3)

In [26]:
print(np.size(matrix_a_2))

9


In [27]:
print(matrix_a_2.shape)

(3, 3)


In [28]:
print(matrix_a.shape)

(3, 3)


In [29]:
print(array_b.shape)

(3,)


In [30]:
print(matrix_a)
print(array_b)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[10 11 12]


In [31]:
mat_c = np.matmul(matrix_a,array_b)
print(mat_c)

[ 35. 134. 233.]


In [32]:
print(mat_c.shape)

(3,)
